#!/usr/bin/env python3
"""Generate the Sources & notes list in ../sections/footer.html from ../data/sources.json.

The page is assembled Jekyll-style (see ../README.md): index.html is the main
file and each section lives in ../sections/. This script:

- Rewrites everything between the REFS:START and REFS:END markers in
  sections/footer.html.
- Groups sources by area (in the order listed in sources.json "areas").
- Verifies that every in-text citation (href="#ref-<citekey>") anywhere in the
  page (index.html + all section files) resolves to a source, and that every
  source is cited at least once.

Writes atomically (temp file + rename) so a concurrently open editor never
sees a half-written file. Exits non-zero on validation failure.
"""

import json
import re
import sys
import tempfile
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FOOTER = ROOT / "sections" / "footer.html"
SOURCES = ROOT / "data" / "sources.json"

START = "<!-- REFS:START"
END = "<!-- REFS:END -->"


def render(data):
    by_area = {}
    for s in data["sources"]:
        by_area.setdefault(s["area"], []).append(s)

    out = [
        "  <!-- REFS:START — generated by scripts/build_references.py"
        " from data/sources.json; do not edit by hand -->"
    ]
    for area in data["areas"]:
        entries = by_area.pop(area, [])
        if not entries:
            continue
        out.append(f'  <p class="refarea">{escape(area)}</p>')
        out.append("  <ol>")
        for s in sorted(entries, key=lambda s: (s["authors"], s["year"])):
            title = escape(s["title"])
            linked = (
                f'<a href="{escape(s["url"], quote=True)}" target="_blank" rel="noopener">{title}</a>'
                if s["url"]
                else f"<i>{title}</i>"
            )
            # quote_source provenance stays in data/sources.json, not on the page
            out.append(
                f'    <li id="ref-{s["citekey"]}">{escape(s["authors"])} '
                f'({s["year"]}). {linked}. {escape(s["venue"])}.'
                f'<span class="finding">{escape(s["finding"])}</span></li>'
            )
        out.append("  </ol>")
    if by_area:
        sys.exit(f"sources.json areas list is missing: {sorted(by_area)}")
    out.append("  " + END)
    return "\n".join(out)


def main():
    data = json.loads(SOURCES.read_text(encoding="utf-8"))
    footer = FOOTER.read_text(encoding="utf-8")

    keys = [s["citekey"] for s in data["sources"]]
    dupes = {k for k in keys if keys.count(k) > 1}
    if dupes:
        sys.exit(f"duplicate citekeys in sources.json: {sorted(dupes)}")

    start = footer.find(START)
    stop = footer.find(END)
    if start == -1 or stop == -1:
        sys.exit("REFS markers not found in sections/footer.html")

    # citations live across the whole assembled page; scan every source file,
    # with the generated block stripped so stale refs can't mask problems
    body = footer[:start] + footer[stop + len(END):]
    body += (ROOT / "index.html").read_text(encoding="utf-8")
    for f in sorted((ROOT / "sections").glob("*.html")):
        if f.name != "footer.html":
            body += f.read_text(encoding="utf-8")

    cited = set(re.findall(r'href="#ref-([A-Za-z0-9_-]+)"', body))
    known = set(keys)
    problems = []
    if cited - known:
        problems.append(f"citations with no source: {sorted(cited - known)}")
    if known - cited:
        problems.append(f"sources never cited in text: {sorted(known - cited)}")
    if problems:
        sys.exit("; ".join(problems))

    new_footer = footer[:start].rstrip() + "\n" + render(data) + footer[stop + len(END):]
    with tempfile.NamedTemporaryFile(
        "w", dir=FOOTER.parent, suffix=".tmp", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(new_footer)
    Path(tmp.name).replace(FOOTER)
    print(
        f"ok: {len(known)} sources across {len(data['areas'])} areas; "
        f"{len(cited)} cited citekeys all resolve."
    )


if __name__ == "__main__":
    main()
